layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - Resume

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: apophis981
  # instagram: your_username
  # keybase: your_username
  linkedin: jeremyrhurst
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 12407480
  # telegram: your_username
  twitter: Apophis981
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UCj5hWElSZUIR_RDvqdp7opQ

topics:

  - name: Home Automation
    web_url: https://store.google.com/us/product/google_home
    image_url: https://cdn.iconscout.com/icon/premium/png-256-thumb/home-automation-17-726007.png

  - name: Robotics
    image_url: https://cdn.iconscout.com/icon/premium/png-512-thumb/robotics-51-645244.png

  - name: Android
    web_url: android.com
    image_url: https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/001/050/thumb/androidlogo.png

  - name: Google DeepMind
    web_url: https://deepmind.com/
    image_url: https://res-5.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_120,w_120,f_auto,b_white,q_auto:eco/v1424343851/jzb3htgphxrp30uqqojv.png

  - name: IoT
    web_url: https://en.wikipedia.org/wiki/Internet_of_things
    image_url: https://www.hoyads.com/hs-fs/hubfs/images/solution/iot-icon02.png?width=128&height=128&name=iot-icon02.png

  - name: Big Data
    image_url: https://konnector.io/wp-content/uploads/2018/07/database.png
